import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import theme from "../theme";
import { ThemeProvider } from "@mui/material";
import { Provider } from "react-redux";
import Providers from "@/redux/provider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// import { store } from "@/redux/store";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JobTracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        <Providers>
      <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        {children}
        <ToastContainer />
        </ThemeProvider>
        </AppRouterCacheProvider>
        {/* </Provider> */}
        </Providers>
        </body>
    </html>
  );
}


